#!/bin/bash

if mount | grep -q "on / type aufs"; then
    cat <<EOF >&2
WARNING: Generation of wic images will fail!

Your docker host setup uses broken aufs as storage driver. Adjust the docker
configuration to use a different driver (overlay, overlay2, devicemapper). You
may also need to update the host distribution (e.g. Debian Jessie -> Stretch).

EOF
fi



GOSU="gosu builder"

#cd /builder

if [ -n "$1" ]; then
	case "$1" in
	build|checkout|for-all-repos|shell|-*)
		exec $GOSU kas "$@"
		;;
	*)
		exec $GOSU "$@"
		;;
	esac
else
	exec $GOSU bash
fi
